"""Generate LaTeX table bodies from the frozen analysis, so no number is typed by hand.

Run from the repository root:  python paper/tables/make_tables.py
"""
from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "analysis"))

import numpy as np
import pandas as pd

import common as C

TAB = os.path.join(C.REPO, "paper", "tables")
os.makedirs(TAB, exist_ok=True)

HF_ID = {
    "OPT-350M": "facebook/opt-350m", "BLOOM-560M": "bigscience/bloom-560m",
    "Pythia-410M": "EleutherAI/pythia-410m", "BLOOM-1B1": "bigscience/bloom-1b1",
    "TinyLlama-1.1B-Chat": "TinyLlama/TinyLlama-1.1B-Chat-v1.0",
    "Llama-3.2-1B": "meta-llama/Llama-3.2-1B",
    "Cerebras-GPT-1.3B": "cerebras/Cerebras-GPT-1.3B", "OPT-1.3B": "facebook/opt-1.3b",
    "LaMini-GPT-1.5B": "MBZUAI/LaMini-GPT-1.5B", "Qwen1.5-1.8B": "Qwen/Qwen1.5-1.8B",
    "OPT-2.7B": "facebook/opt-2.7b", "BLOOM-3B": "bigscience/bloom-3b",
    "Llama-3.2-3B": "meta-llama/Llama-3.2-3B", "SmolLM3-3B": "HuggingFaceTB/SmolLM3-3B",
    "StableLM-Zephyr-3B": "stabilityai/stablelm-zephyr-3b",
    "Qwen3.5-4B-Base": "Qwen/Qwen3.5-4B-Base", "Qwen3.5-4B": "Qwen/Qwen3.5-4B",
    "Mistral-7B-v0.3": "mistralai/Mistral-7B-v0.3", "Qwen2-7B": "Qwen/Qwen2-7B",
    "Qwen2-7B-Instruct": "Qwen/Qwen2-7B-Instruct", "Gemma-7B": "google/gemma-7b",
    "Zephyr-7B-beta": "HuggingFaceH4/zephyr-7b-beta",
    "Llama-3.1-8B": "meta-llama/Meta-Llama-3.1-8B",
    "Llama-3.1-8B-Instruct": "meta-llama/Llama-3.1-8B-Instruct",
    "Minitron-8B-Base": "nvidia/Minitron-8B-Base", "Hormoz-8B": "mann-e/Hormoz-8B",
    "Gemma-2-9B": "google/gemma-2-9b", "Qwen3.5-9B-Base": "Qwen/Qwen3.5-9B-Base",
    "Qwen3.5-9B": "Qwen/Qwen3.5-9B", "Phi-4-14B": "microsoft/phi-4",
    "Mistral-Nemo-Base-2407": "mistralai/Mistral-Nemo-Base-2407",
}
INSTRUCT = set(C.EXTRINSIC_MODELS)


def w(name, body):
    p = os.path.join(TAB, name)
    with open(p, "w", encoding="utf-8") as f:
        f.write("% Generated by paper/tables/make_tables.py. Do not edit by hand.\n")
        f.write(body if body.endswith("\n") else body + "\n")
    print("wrote", p)


def stars(p):
    if p < 0.001:
        return r"\ssig{***}"
    if p < 0.01:
        return r"\ssig{**}"
    if p < 0.05:
        return r"\ssig{*}"
    return r"\nsig{n.s.}"


def fp(p):
    """Compact p-value."""
    if p < 1e-4:
        return r"$<$\,.0001"
    return f"{p:.4f}".lstrip("0")


# ------------------------------------------------------------- main results --

def extrinsic_main():
    ex = pd.read_csv(os.path.join(C.OUT_DIR, "extrinsic_main.csv"))
    sold = pd.read_csv(os.path.join(C.OUT_DIR, "sold_detail.csv")).set_index("model")
    order = sorted(C.EXTRINSIC_MODELS, key=lambda m: C.EXTRINSIC_MODELS[m][2])
    mm = ex[ex.dataset == "sinhala_mmlu"].set_index("model")
    pq = ex[ex.dataset == "global_piqa"].set_index("model")
    rows = []
    for m in order:
        a, s, q = mm.loc[m], sold.loc[m], pq.loc[m]
        comp = r"$\dagger$" if a.competent and not a.degenerate_u else ""
        name = m.replace("-", "\\nobreakdash-")
        rows.append(
            f"{name}{comp} & {C.EXTRINSIC_MODELS[m][2]:.1f} "
            f"& {a.u_acc:.1f} & {a.r_acc:.1f} & {a.gap:+.1f} "
            f"& [{a.gap_lo:.1f},{a.gap_hi:.1f}] & {fp(a.p_holm)} "
            f"& {s.u_macroF1:.1f} & {s.r_macroF1:.1f} "
            f"& {s.u_mcc:.3f} & {s.r_mcc:.3f} & {fp(s.dMCC_p_holm)} "
            f"& {a.u_invalid:.1f} & {a.r_invalid:.1f} & {a.tok_ratio:.2f} \\\\")
    w("tab_extrinsic_main.tex", "\n".join(rows))

    # Global PIQA moves to the appendix: 100 items cannot support a main-text column.
    prows = []
    for m in order:
        q, a = pq.loc[m], mm.loc[m]
        prows.append(f"{m.replace('-', chr(92)+'nobreakdash-')} & {q.u_acc:.0f} & {q.r_acc:.0f} "
                     f"& {q.gap:+.0f} & {q.b:.0f}/{q.c:.0f} & {fp(q.p_holm)} "
                     f"& {q.u_invalid:.0f} & {q.r_invalid:.0f} \\\\")
    w("tab_piqa.tex", "\n".join(prows))


def strata():
    dif = pd.read_csv(os.path.join(C.OUT_DIR, "mmlu_by_difficulty.csv"))
    dom = pd.read_csv(os.path.join(C.OUT_DIR, "mmlu_by_domain.csv"))
    dif["difficulty"] = pd.Categorical(dif.difficulty, ["Easy", "Medium", "Hard"])
    dif = dif.sort_values("difficulty")
    dom = dom.sort_values("gap", ascending=False)
    lines = [r"\multicolumn{6}{@{}l}{\emph{by difficulty}} \\"]
    for r in dif.itertuples():
        lines.append(f"\\quad {r.difficulty} & {r.n_items:,} & {r.u_acc:.1f} & {r.r_acc:.1f} "
                     f"& {r.gap:.1f} & {fp(r.p_holm)} \\\\")
    lines.append(r"\addlinespace[2pt]")
    lines.append(r"\multicolumn{6}{@{}l}{\emph{by domain}} \\")
    for r in dom.itertuples():
        nm = r.domain.replace("_", " ")
        lines.append(f"\\quad {nm} & {r.n_items:,} & {r.u_acc:.1f} & {r.r_acc:.1f} "
                     f"& {r.gap:.1f} & {fp(r.p_holm)} \\\\")
    w("tab_strata.tex", "\n".join(lines))


def methods():
    t = pd.read_csv(os.path.join(C.REPO, "results", "method_evaluation", "results_table.csv"),
                    encoding="utf-8-sig")
    label = {"phonetic": r"\textbf{Ours}", "nisansa_w": r"Web tool $v\!\to\!w$",
             "nisansa_sirs_method": "Web tool, raw",
             "aksharamukha": "Aksharamukha", "uroman": "uroman"}
    order = ["phonetic", "nisansa_w", "aksharamukha", "nisansa_sirs_method", "uroman"]
    corp = [("social_media", "sent."), ("swa_bhasha_words", "word"),
            ("augmented_sentences_sample", "aug.")]
    rows = []
    for meth in order:
        cells = []
        for c, _ in corp:
            r = t[(t.corpus == c) & (t.method == meth)].iloc[0]
            best = t[t.corpus == c].cer.min()
            v = f"{r.cer:.3f}"
            cells.append(r"\textbf{" + v + "}" if abs(r.cer - best) < 1e-9 else v)
        r0 = t[(t.corpus == "social_media") & (t.method == meth)].iloc[0]
        rw = t[(t.corpus == "swa_bhasha_words") & (t.method == meth)].iloc[0]
        cov = min(t[t.method == meth].coverage_pct)
        rows.append(f"{label[meth]} & " + " & ".join(cells) +
                    f" & {r0.chrf:.1f} & {rw.exact_pct:.1f} & {cov:.2f} \\\\")
    w("tab_methods.tex", "\n".join(rows))


def intrinsic_full():
    it = pd.read_csv(os.path.join(C.OUT_DIR, "intrinsic_pooled.csv")).sort_values("u_bpb")
    rows = []
    for r in it.itertuples():
        tag = r"$\ddagger$" if r.model in INSTRUCT else ""
        rows.append(
            f"{r.model.replace('-', chr(92)+'nobreakdash-')}{tag} & {r.params:.1f} "
            f"& {r.u_ppl:.2f} & {r.u_bpb:.3f} & {r.u_bpw:.2f} "
            f"& {r.r_ppl:.1f} & {r.r_bpb:.3f} & {r.r_bpw:.2f} "
            f"& {r.m_ppl:.2f} & {r.m_bpb:.3f} & {r.m_bpw:.2f} \\\\")
    w("tab_intrinsic_full.tex", "\n".join(rows))


def model_ids():
    it = pd.read_csv(os.path.join(C.OUT_DIR, "intrinsic_pooled.csv")).sort_values("params")
    rows = []
    for r in it.itertuples():
        tag = r"$\ddagger$" if r.model in INSTRUCT else ""
        rows.append(f"{r.model}{tag} & {r.params:.2f} & \\texttt{{{HF_ID[r.model]}}} "
                    f"& {r.u_tok_per_word:.1f} & {r.r_tok_per_word:.1f} \\\\")
    w("tab_model_ids.tex", "\n".join(rows))


def ngram():
    ni = json.load(open(os.path.join(C.OUT_DIR, "intrinsic_numbers.json")))
    it = pd.read_csv(os.path.join(C.OUT_DIR, "intrinsic_pooled.csv"))
    rows = []
    for order in range(6):
        u = ni["ngram_reference"]["unicode"][f"order{order}"]["bpb"]
        r = ni["ngram_reference"]["romanized"][f"order{order}"]["bpb"]
        nu = int((it.u_bpb < u).sum())
        nr = int((it.r_bpb < r).sum())
        rows.append(f"character {order+1}-gram & {u:.3f} & {nu} & {r:.3f} & {nr} \\\\")
    rows.append(r"\addlinespace[2pt]")
    rows.append(f"best checkpoint & {it.u_bpb.min():.3f} & -- & {it.r_bpb.min():.3f} & -- \\\\")
    rows.append(f"median checkpoint & {it.u_bpb.median():.3f} & -- & {it.r_bpb.median():.3f} & -- \\\\")
    w("tab_ngram.tex", "\n".join(rows))


def linkage():
    lk = pd.read_csv(os.path.join(C.OUT_DIR, "linkage.csv"))
    ne = json.load(open(os.path.join(C.OUT_DIR, "extrinsic_numbers.json")))
    L = ne["linkage"]
    names = [("u_bpb", "Unicode BPB (level)"), ("r_bpb", "Romanized BPB (level)"),
             ("d_bpb", "BPB gap (Rom. $-$ Uni.)"), ("u_bpw", "Unicode BPW (level)"),
             ("ppl_ratio", "perplexity ratio"), ("params", "parameter count")]
    rows = []
    for k, lab in names:
        a = L[f"{k}~mmlu_gap"]
        b = L[f"{k}~sold_d_mcc"]
        rows.append(f"{lab} & ${a['rho']:+.2f}$ & {fp(a['p'])} & ${b['rho']:+.2f}$ & {fp(b['p'])} \\\\")
    w("tab_linkage.tex", "\n".join(rows))


if __name__ == "__main__":
    extrinsic_main()
    strata()
    methods()
    intrinsic_full()
    model_ids()
    ngram()
    linkage()
