"""Build every figure and table this paper needs, at NeurIPS page geometry.

The NeurIPS style is single column with a 5.5 inch text width, so the figures
are regenerated at that width rather than scaled down from the two-column
versions, which would shrink their labels below legibility.

Table bodies are copied into ./tables/ rather than referenced across
directories, so this folder can be uploaded to Overleaf on its own. Two
fragments are specific to this paper and generated here:

    tab_gs_decomp.tex      the compact decomposition summary
    tab_gs_intrinsic.tex   all 31 checkpoints in one block, narrow enough for
                           a 5.5 inch page

Run from the repository root:  python paper/globalsouthai/make_assets.py
"""
from __future__ import annotations

import json
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PAPER = os.path.dirname(HERE)
REPO = os.path.dirname(PAPER)
sys.path.insert(0, os.path.join(PAPER, "analysis"))
sys.path.insert(0, os.path.join(PAPER, "figures"))

import pandas as pd

import common as C

FIG = os.path.join(HERE, "figures")
TAB = os.path.join(HERE, "tables")
SRC_TAB = os.path.join(PAPER, "tables")

# Fragments reused verbatim from the long version. They are row bodies only, so
# the column specification and font size live in this paper's .tex file.
REUSE = [
    "tab_extrinsic_main.tex",   # downstream results, 11 checkpoints
    "tab_strata.tex",           # SinhalaMMLU by difficulty and domain
    "tab_piqa.tex",             # Global PIQA per checkpoint
    "tab_invalid_tau.tex",      # unparseable rates and token ratios
    "tab_linkage.tex",          # intrinsic measurements against script effects
    "tab_flatten.tex",          # every refit of the flattening regressions
    "tab_decomp.tex",           # per-checkpoint perplexity decomposition
    "tab_shared24.tex",         # reproduction of the published benchmark
    "tab_methods.tex",          # transliteration quality against human refs
    "tab_attest.tex",           # spelling attestation
    "tab_attest_tercile.tex",   # does attestation predict the penalty
    "tab_mismatch.tex",         # most frequent disagreements with human typing
    "tab_svh.tex",              # our transliteration scored against human typing
    "tab_pilot.tex",            # the prompt-template pilot
    "tab_ngram.tex",            # character n-gram references
    "tab_model_ids.tex",        # Hugging Face identifiers and fertility
]


def w(name: str, body: str) -> None:
    p = os.path.join(TAB, name)
    with open(p, "w", encoding="utf-8") as f:
        f.write("% Generated by paper/globalsouthai/make_assets.py. "
                "Do not edit by hand.\n")
        f.write(body if body.endswith("\n") else body + "\n")
    print("wrote", os.path.relpath(p, REPO))


def nb(name: str) -> str:
    return name.replace("-", "\\nobreakdash-")


# ------------------------------------------------------------------ tables ----
def decomp_summary(rb: dict) -> None:
    """The compact split of the reported degradation ratio, for the main body."""
    s = rb["decomposition"]["shared24"]
    a = rb["decomposition"]
    rows = [
        f"reported degradation, Rom.\\ over Sinhala & {s['median_total_bits']:.2f} "
        f"& {s['median_total_factor']:.0f}$\\times$ & "
        f"{a['median_total_factor']:.0f}$\\times$ \\\\",
        r"\addlinespace[2pt]",
        f"\\quad token-count normaliser & {s['median_tok_term_bits']:.2f} "
        f"& {s['median_tok_factor']:.0f}$\\times$ & "
        f"{a['median_tok_factor']:.1f}$\\times$ \\\\",
        f"\\quad per-byte loss & {s['median_loss_term_bits']:.2f} "
        f"& {s['median_loss_factor']:.0f}$\\times$ & "
        f"{a['median_loss_factor']:.1f}$\\times$ \\\\",
        r"\addlinespace[2pt]",
        f"normaliser share of the total & "
        f"{s['median_tok_share_pct']:.0f}\\% & & "
        f"{a['median_tok_share_pct']:.0f}\\% \\\\",
    ]
    w("tab_gs_decomp.tex", "\n".join(rows))


def intrinsic_single_block(it: pd.DataFrame) -> None:
    """All 31 checkpoints in one block, narrow enough for a 5.5 inch page."""
    instruct = set(C.EXTRINSIC_MODELS)
    rows = []
    for r in it.sort_values("u_bpb").itertuples():
        tag = r"$\ddagger$" if r.model in instruct else ""
        rows.append(
            f"{nb(r.model)}{tag} & {r.params:.1f} "
            f"& {r.u_ppl:.2f} & {r.u_bpb:.3f} & {r.u_bpw:.1f} "
            f"& {r.r_ppl:.0f} & {r.r_bpb:.3f} & {r.r_bpw:.1f} "
            f"& {r.m_ppl:.2f} & {r.m_bpb:.3f} \\\\")
    w("tab_gs_intrinsic.tex", "\n".join(rows))


# ----------------------------------------------------------------- figures ----
def figures() -> None:
    """Regenerate at NeurIPS width by overriding the figure module's geometry."""
    import make_figures as MF

    MF.WIDE = 5.5          # full text width
    MF.COL = 5.5           # single column, so "column width" is the text width
    MF.H1 = 1.90           # shorter than the ACL version: a four page budget
                           # cannot afford 2.6 inches of figure, and reducing
                           # the height rather than the width keeps the labels
                           # at their original size
    MF.SPREAD_DY_A = 8     # the shorter panel puts the (a) spread label on a y tick
    MF.FIG = FIG
    os.makedirs(FIG, exist_ok=True)

    it, ex, sold, strata, ni, ne, rb = MF.load()
    MF.fig1(it, ex, ni, ne, rb)          # three panels, main body
    MF.fig2(it, ni)                      # perplexity artifact, appendix
    MF.fig3(ex, sold, strata, ne, rb)    # SOLD Matthews, appendix
    MF.fig4(it, ni)                      # n-gram reference, appendix
    MF.fig5(it)                          # decomposition bars, appendix


def main() -> None:
    os.makedirs(TAB, exist_ok=True)
    os.makedirs(FIG, exist_ok=True)

    it = pd.read_csv(os.path.join(C.OUT_DIR, "intrinsic_pooled.csv"))
    rb = json.load(open(os.path.join(C.OUT_DIR, "robustness_numbers.json")))

    for fn in REUSE:
        src = os.path.join(SRC_TAB, fn)
        if not os.path.exists(src):
            print("MISSING", fn)
            continue
        shutil.copyfile(src, os.path.join(TAB, fn))
    print(f"copied {len(REUSE)} shared table bodies into "
          f"{os.path.relpath(TAB, REPO)}")

    decomp_summary(rb)
    intrinsic_single_block(it)
    figures()


if __name__ == "__main__":
    main()
