"""Build every figure and table this paper needs, at NeurIPS page geometry.

The NeurIPS style is single column with a 5.5 inch text width, so the figures
are regenerated at that width rather than scaled down from the two-column
versions, which would shrink their labels below legibility.

Table bodies are copied into ./tables/ rather than referenced across
directories, so this folder can be uploaded to Overleaf on its own. Two
fragments are specific to this paper and generated here:

    tab_gs_decomp.tex      the compact decomposition summary
    tab_gs_intrinsic.tex   all 31 checkpoints in one block, narrow enough for
                           a 5.5 inch page

Run from the repository root:  python paper/globalsouthai/make_assets.py
"""
from __future__ import annotations

import json
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PAPER = os.path.dirname(HERE)
REPO = os.path.dirname(PAPER)
sys.path.insert(0, os.path.join(PAPER, "analysis"))
sys.path.insert(0, os.path.join(PAPER, "figures"))

import pandas as pd

import common as C

FIG = os.path.join(HERE, "figures")
TAB = os.path.join(HERE, "tables")
SRC_TAB = os.path.join(PAPER, "tables")

# Fragments reused verbatim from the long version. They are row bodies only, so
# the column specification and font size live in this paper's .tex file.
REUSE = [
    "tab_extrinsic_main.tex",   # downstream results, 11 checkpoints
    "tab_strata.tex",           # SinhalaMMLU by difficulty and domain
    "tab_piqa.tex",             # Global PIQA per checkpoint
    "tab_invalid_tau.tex",      # unparseable rates and token ratios
    "tab_linkage.tex",          # intrinsic measurements against script effects
    "tab_flatten.tex",          # every refit of the flattening regressions
    "tab_decomp.tex",           # per-checkpoint perplexity decomposition
    "tab_shared24.tex",         # reproduction of the published benchmark
    "tab_methods.tex",          # transliteration quality against human refs
    "tab_attest.tex",           # spelling attestation
    "tab_attest_tercile.tex",   # does attestation predict the penalty
    "tab_mismatch.tex",         # most frequent disagreements with human typing
    "tab_svh.tex",              # our transliteration scored against human typing
    "tab_pilot.tex",            # the prompt-template pilot
    "tab_ngram.tex",            # character n-gram references
    "tab_model_ids.tex",        # Hugging Face identifiers and fertility
]


def w(name: str, body: str) -> None:
    p = os.path.join(TAB, name)
    with open(p, "w", encoding="utf-8") as f:
        f.write("% Generated by paper/globalsouthai/make_assets.py. "
                "Do not edit by hand.\n")
        f.write(body if body.endswith("\n") else body + "\n")
    print("wrote", os.path.relpath(p, REPO))


def nb(name: str) -> str:
    return name.replace("-", "\\nobreakdash-")


# ------------------------------------------------------------------ tables ----
def decomp_summary(rb: dict) -> None:
    """The compact split of the reported degradation ratio, for the main body."""
    s = rb["decomposition"]["shared24"]
    a = rb["decomposition"]
    rows = [
        f"reported degradation, Rom.\\ over Sinhala & {s['median_total_bits']:.2f} "
        f"& {s['median_total_factor']:.0f}$\\times$ & "
        f"{a['median_total_factor']:.0f}$\\times$ \\\\",
        r"\addlinespace[2pt]",
        f"\\quad token-count normaliser & {s['median_tok_term_bits']:.2f} "
        f"& {s['median_tok_factor']:.0f}$\\times$ & "
        f"{a['median_tok_factor']:.1f}$\\times$ \\\\",
        f"\\quad per-byte loss & {s['median_loss_term_bits']:.2f} "
        f"& {s['median_loss_factor']:.0f}$\\times$ & "
        f"{a['median_loss_factor']:.1f}$\\times$ \\\\",
        r"\addlinespace[2pt]",
        f"normaliser share of the total & "
        f"{s['median_tok_share_pct']:.0f}\\% & & "
        f"{a['median_tok_share_pct']:.0f}\\% \\\\",
    ]
    w("tab_gs_decomp.tex", "\n".join(rows))


def intrinsic_single_block(it: pd.DataFrame) -> None:
    """All 31 checkpoints in one block, narrow enough for a 5.5 inch page."""
    instruct = set(C.EXTRINSIC_MODELS)
    rows = []
    for r in it.sort_values("u_bpb").itertuples():
        tag = r"$\ddagger$" if r.model in instruct else ""
        rows.append(
            f"{nb(r.model)}{tag} & {r.params:.1f} "
            f"& {r.u_ppl:.2f} & {r.u_bpb:.3f} & {r.u_bpw:.1f} "
            f"& {r.r_ppl:.0f} & {r.r_bpb:.3f} & {r.r_bpw:.1f} "
            f"& {r.m_ppl:.2f} & {r.m_bpb:.3f} \\\\")
    w("tab_gs_intrinsic.tex", "\n".join(rows))


# ----------------------------------------------------------------- figures ----
def fig1_combined(MF, it, ex, ne, rb) -> None:
    """Figure 1 as the single three-panel PDF this paper includes.

    The long version now draws one PDF per panel and places them as subfigures;
    this paper keeps one graphic, so the same panel functions are laid out here
    on one canvas. Panel (c) labels its two fits directly on the lines rather
    than only in a legend, which reviewer sWb1 asked for: that panel is where
    the two slopes first appear.
    """
    import matplotlib.pyplot as plt

    m = MF._mmlu_frame(ex)
    fig, (a, b, c) = plt.subplots(
        1, 3, figsize=(MF.WIDE, MF.H1),
        gridspec_kw=dict(wspace=0.40, width_ratios=[1, 1, 1.5]))
    MF._panel_lm_cost(a, it, prefix="(a) ")
    MF._panel_mmlu_acc(b, m, ne, prefix="(b) ")
    MF._panel_transfer(c, m, ne, rb, prefix="(c) ")

    # direct labels at the right-hand end of each fitted line
    lv = rb["flattening_models"]["levels"]
    cl = rb["flattening_cells"]["levels"]
    n_cells = len(MF.strata_for_panel())
    x_end = 45.8
    c.annotate(f"{n_cells} cells, slope {cl['slope']:.2f}",
               (x_end, cl["intercept"] + cl["slope"] * x_end),
               xytext=(0, 4), textcoords="offset points",
               fontsize=5.7, color=MF.MIX, ha="right", va="bottom")
    # in the empty lower-right corner, with a leader to the line, because the
    # line itself runs through the highest checkpoints and the cell markers
    x_hit = 41.0
    c.annotate(f"{len(m)} checkpoints\nslope {lv['slope']:.2f}",
               xy=(x_hit, lv["intercept"] + lv["slope"] * x_hit),
               xytext=(x_end, 25.3), fontsize=5.7, color=MF.UNI,
               ha="right", va="top", linespacing=1.1,
               arrowprops=dict(arrowstyle="-", color=MF.UNI, lw=0.5,
                               shrinkA=1, shrinkB=1))
    leg = c.get_legend()
    if leg is not None:
        leg.remove()
    MF.save(fig, "fig1_flattening")


def figures() -> None:
    """Regenerate at NeurIPS width by overriding the figure module's geometry."""
    import make_figures as MF

    MF.WIDE = 5.5          # full text width
    MF.COL = 5.5           # single column, so "column width" is the text width
    MF.H1 = 1.90           # shorter than the ACL version: a four page budget
                           # cannot afford 2.6 inches of figure, and reducing
                           # the height rather than the width keeps the labels
                           # at their original size
    MF.SPREAD_DY_A = 8     # the shorter panel puts the (a) spread label on a y tick
    MF.FIG = FIG
    os.makedirs(FIG, exist_ok=True)

    it, ex, sold, strata, ni, ne, rb = MF.load()
    fig1_combined(MF, it, ex, ne, rb)    # three panels on one canvas, main body
    # The appendix figures fig2-fig5 are the committed PDFs. The long version's
    # figure module now writes fig2 as separate per-panel files, which this
    # paper does not include, so they are not regenerated here.


def figure1_only() -> None:
    """Rebuild only Figure 1, leaving every table and appendix figure untouched."""
    import make_figures as MF

    MF.WIDE, MF.COL, MF.H1, MF.SPREAD_DY_A, MF.FIG = 5.5, 5.5, 1.90, 8, FIG
    it, ex, sold, strata, ni, ne, rb = MF.load()
    fig1_combined(MF, it, ex, ne, rb)


def main() -> None:
    os.makedirs(TAB, exist_ok=True)
    os.makedirs(FIG, exist_ok=True)

    it = pd.read_csv(os.path.join(C.OUT_DIR, "intrinsic_pooled.csv"))
    rb = json.load(open(os.path.join(C.OUT_DIR, "robustness_numbers.json")))

    for fn in REUSE:
        src = os.path.join(SRC_TAB, fn)
        if not os.path.exists(src):
            print("MISSING", fn)
            continue
        shutil.copyfile(src, os.path.join(TAB, fn))
    print(f"copied {len(REUSE)} shared table bodies into "
          f"{os.path.relpath(TAB, REPO)}")

    decomp_summary(rb)
    intrinsic_single_block(it)
    figures()


if __name__ == "__main__":
    if "--figure1" in sys.argv:
        figure1_only()
    else:
        main()
